export const ProductsData = [
    {
        'id': 1,
        'name': 'Carrot',
        'note':'1kg',
        'price': 25,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/Carrots.jpg',
        'id_category': 1,

    },
    {
        'id': 2,
        'name': 'Cabbage',
        'note':'1kg',
        'price': 15,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/Cabbages.jpg',
        'id_category': 1,
        
    },
    {
        'id': 3,
        'name': 'Onion',
        'note':'1kg',
        'price': 10,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/onions.jpg',
        'id_category': 1,
        
    },
    {
        'id': 4,
        'name': 'Potato',
        'note':'1kg',
        'price': 9,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/potatoes.jpeg',
        'id_category': 1,
        
    },
    {
        'id': 5,
        'name': 'Pumpkin',
        'note':'1kg',
        'price': 12,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/pumpkins.jpg',
        'id_category': 1,
        
    },
    {
        'id': 6,
        'name': 'Broccoli',
        'note':'1kg',
        'price': 15,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/broccoli.jpg',
        'id_category': 1,
        
    },
    {
        'id': 7,
        'name': 'Egg Plant',
        'note':'1kg',
        'price': 8,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/eggplants.jpg',
        'id_category': 1,
        
    },
    {
        'id': 8,
        'name': 'Tomato',
        'note':'1kg',
        'price': 6,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/Tomatos.jpg',
        'id_category': 1,
        
    },
    {
        'id': 9,
        'name': 'Apple',
        'note':'1kg',
        'price': 12,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/apples.jpg',
        'id_category': 2,
        
    },
    {
        'id': 10,
        'name': 'Banana',
        'note':'1kg',
        'price': 10,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/bananas.jpg',
        'id_category': 2,
        
    },
    {
        'id': 11,
        'name': 'Watermelon',
        'note':'1kg',
        'price': 8,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/Watermelons.jpeg',
        'id_category': 2,
        
    },
    {
        'id': 12,
        'name': 'Orange',
        'note':'1kg',
        'price': 9,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/oranges.jpg',
        'id_category': 2,
        
    },
    {
        'id': 13,
        'name': 'Strawberry',
        'note':'500g',
        'price': 13,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/strawberrys.jpg',
        'id_category': 2,
        
    },
    {
        'id': 14,
        'name': 'Mango',
        'note':'1kg',
        'price': 11,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/mangos.jpg',
        'id_category': 2,
        
    },
    {
        'id': 15,
        'name': 'Papaya',
        'note':'1kg',
        'price': 8,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/papaya.jpeg',
        'id_category': 2,
        
    },
    {
        'id': 16,
        'name': 'Pineapple',
        'note':'1kg',
        'price': 15,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/pineapples.jpg',
        'id_category': 2,
        
    },
    {
        'id': 17,
        'name': 'Lipstick',
        'note':'Diverse range of brands and colors.',
        'price': 15,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/lipsticks.jpg',
        'id_category': 3,
        
    },
    {
        'id': 18,
        'name': 'Cream - 50ml',
        'note':'Variety of skincare and beauty creams.',
        'price': 20,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/creams.jpeg',
        'id_category': 3,
        
    },
    {
        'id': 19,
        'name': 'Face Wash - 100ml',
        'note':'Diverse skincare and beauty collection',
        'price': 18,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/facewash.jpg',
        'id_category': 3,
        
    },
    {
        'id': 20,
        'name': 'Nail polish - 1ml',
        'note':'Diverse range of brands and colors.',
        'price': 17,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/nailpolish.jpg',
        'id_category': 3,
        
    },
    {
        'id': 21,
        'name': 'Perfume - 100ml',
        'note':'Variety of brands and irresistible scents',
        'price': 21,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/perfumes.jpeg',
        'id_category': 3,
        
    },
    {
        'id': 22,
        'name': 'Powder - 25g',
        'note':'Diverse powders, perfect for all skin tones.',
        'price': 18,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/powders.jpg',
        'id_category': 3,
        
    },
    {
        'id': 23,
        'name': 'Shampoo - 500ml',
        'note':'Diverse shampoos for every hair type.',
        'price': 25,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/shampoo.jpg',
        'id_category': 3,
        
    },
    {
        'id': 24,
        'name': 'Soap - 1bar',
        'note':'Diverse range of exquisite scents soap',
        'price': 10,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/soaps.jpg',
        'id_category': 3,
        
    },
    {
        'id': 25,
        'name': 'Soda Bottle - 1L',
        'note':'Elephant House, Coca-cola, Sprite, Fanta',
        'price': 20,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/Bottlesoda.jpg',
        'id_category': 4,
        
    },
    {
        'id': 26,
        'name': 'Soda Can - 350ml',
        'note':'Elephant House, Coca-cola, Sprite, Fanta',
        'price': 15,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/sodacan.jpg',
        'id_category': 4,
        
    }
    ,
    {
        'id': 27,
        'name': 'Milk - 1L',
        'note':'Ambewela, Anchor, Maliban, Kotmale, Rich Life, Highland',
        'price': 18,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/milk.jpeg',
        'id_category': 4,
        
    },
    ,
    {
        'id': 28,
        'name': 'Youget Drink - 500ml',
        'note':'Kotmale, Chello, Rich Life, Anchor, Creamoo, Richi',
        'price': 13,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/youget.jpg',
        'id_category': 4,
        
    },
    ,
    {
        'id': 29,
        'name': 'Juice Bottle - 500ml',
        'note':'Smak, Kist, MD, Sunquick',
        'price': 18,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/juicbottle.jpg',
        'id_category': 4,
        
    },
    ,
    {
        'id': 30,
        'name': 'Alcohol - 1L',
        'note':'Beer, Wine, Whisky, Brandy, Vodka ',
        'price': 27,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/alcohol.jpg',
        'id_category': 4,
        
    },
    ,
    {
        'id': 31,
        'name': 'Fresh Juice - 150ml',
        'note':'Orange, Mango, Watermelon, Papaya, Pineapple',
        'price': 21,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/juice.jpg',
        'id_category': 4,
        
    },
    ,
    {
        'id': 32,
        'name': 'Cocktail Juice - 300ml',
        'note':'Mojito, Margarita, Negroni, Martini, Gimlet, Mimosa',
        'price': 24,
        'devise': '$',
        'available': 1000,
        'urlImage': '/products/freachjuice.jpeg',
        'id_category': 4,
        
    }
    
]